### ISSUE TITLE
Allow analytics to be disabled

### ISSUE THREAD

**Issue by jergason** [joshbalfour/disable-scroll-jacking#10]
This is a neat thing. I'd love to use it. From reading the code it looks like you are injecting Google Analytics in order to track events related to the extension - when it blocks scroll jacking, if there are any errors thrown etc?

I'm not a huge fan of the extension tracking my behavior like this. My plan is just to grab the code, remove the analytics stuff and run this locally. However, that means I lose out on bug fixes, updates, etc.

Would you consider some kind of setting that disables the analytics part of the extension and just keeps the part that disables scroll-jacking? This is your project and I'm asking you to do work for free for my convenience so "no" is totally a fine answer. In that case I'd stick to copy-pasting the code to a local developer extension, but I wonder if there are other people concerned about privacy stuff as well.

**Comment by joshbalfour** [comment]
Thanks for the feedback!

You can currently disable the analytics completely by right clicking on the extension, hitting options

![image](https://cloud.githubusercontent.com/assets/1060378/15603519/1a90a8e4-23f3-11e6-88f1-5fd176cb04a5.png)

Unchecking the checkbox and hitting save.
![image](https://cloud.githubusercontent.com/assets/1060378/15603525/25aff842-23f3-11e6-8eb3-41bd1c2a2f5b.png)


I've had a lot of feedback about this and in the next major update will definitely be changing the way this works or ripping it out completely.

**Comment by jergason** [comment]
Neat!
