### ISSUE TITLE
"Save" button cannot be clicked

### ISSUE THREAD

**Issue by EdenSG** [joshbalfour/disable-scroll-jacking#12]
In the panel that opens when the toolbar icon is clicked, the button to save the strictness level cannot be clicked, however it can be navigated to with the keyboard. Any idea why?

**Comment by neilzo** [comment]
Getting this as well. The option panel when in chrome://extensions is totally unresponsive too.

**Comment by joshbalfour** [comment]
Thanks for reporting!

**Comment by joshbalfour** [comment]
This has been fixed in the v0.0.2 update, you should see it pushed to your browser within the next hour.
